import json
import zipfile
from io import BytesIO
from pathlib import Path
from typing import Any

from .domain import canonical, digest


def packet(case: dict[str, Any]) -> tuple[str, bytes, str, str]:
    manifest = {"case_id": case["id"], "digest": case["digest"], "evidence": case["evidence_ids"],
                "approvals": case["approvals"], "mode": "exercise"}
    body = f"""<!doctype html><html><head><meta charset="utf-8"><title>Activation Decision Packet</title>
<style>body{{font-family:Arial,sans-serif;max-width:860px;margin:32px auto;line-height:1.5}}table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #ddd;padding:8px;text-align:left}}code{{overflow-wrap:anywhere}}</style></head><body>
<h1>Activation Decision Packet</h1><p><strong>Exercise:</strong> Linda records a recommendation for human authorisation; it does not dispatch alerts or release funds.</p>
<h2>{case['title']}</h2><p>Case digest: <code>{case['digest']}</code></p><h2>Policy gates</h2><table><tr><th>Gate</th><th>Result</th><th>Basis</th></tr>
{''.join(f"<tr><td>{gate['name']}</td><td>{'PASS' if gate['passed'] else 'FAIL'}</td><td>{gate['basis']}</td></tr>" for gate in case['assessment']['gates'])}</table>
<h2>Approvals</h2><pre>{json.dumps(case['approvals'], indent=2)}</pre><h2>Manifest</h2><pre>{json.dumps(manifest, indent=2)}</pre></body></html>"""
    return "packet", body.encode(), "text/html", digest(manifest)


def cap(case: dict[str, Any], cancel: bool = False) -> tuple[str, bytes, str, str | None]:
    message_type = "Cancel" if cancel else "Alert"
    headline = f"Exercise cancellation: {case['title']}" if cancel else case["title"]
    description = "Activation recommendation revoked after a stop trigger." if cancel else "Demonstration alert generated by Linda Protocol."
    reference = f"<references>linda-protocol@example.invalid,{case['id']},2026-07-22T09:00:00Z</references>" if cancel else ""
    body = f"""<?xml version="1.0" encoding="UTF-8"?><alert xmlns="urn:oasis:names:tc:emergency:cap:1.2">
<identifier>{case['id']}{'-cancel' if cancel else ''}</identifier><sender>linda-protocol@example.invalid</sender><sent>2026-07-31T00:00:00Z</sent><status>Exercise</status><msgType>{message_type}</msgType><scope>Public</scope>{reference}
<info><category>Met</category><event>Drought activation readiness</event><urgency>{'Past' if cancel else 'Expected'}</urgency><severity>{'Unknown' if cancel else 'Severe'}</severity><certainty>{'Observed' if cancel else 'Likely'}</certainty><headline>{headline}</headline><description>{description} Linda Protocol does not dispatch public alerts.</description><area><areaDesc>Bungoma, Kenya</areaDesc></area></info></alert>"""
    return "cap-cancel" if cancel else "cap", body.encode(), "application/xml", None


def husika(case: dict[str, Any]) -> tuple[str, bytes, str, str | None]:
    payload = {"mode": "exercise", "schema": "husika-ingestor-v1", "case_id": case["id"], "area": case["area"],
               "hazard": case["hazard"], "language": "en", "message": "Demonstration: Bungoma drought activation is approved for authorised Husika operator dispatch.",
               "does_not_dispatch": True, "source_digest": case["digest"]}
    return "husika", canonical(payload).encode(), "application/json", None


def bundle(case: dict[str, Any]) -> tuple[str, bytes, str, str]:
    manifest = {"case_id": case["id"], "digest": case["digest"], "mode": "exercise", "evidence": case["evidence_ids"]}
    contents = {"offline-dossier.html": f"<h1>{case['title']}</h1><p>Digest: {case['digest']}</p>".encode(),
                "manifest.json": json.dumps(manifest, indent=2, sort_keys=True).encode(),
                "cap.xml": cap(case)[1]}
    manifest["checksums"] = {name: digest(data.decode(errors="replace")) for name, data in contents.items()}
    contents["manifest.json"] = json.dumps(manifest, indent=2, sort_keys=True).encode()
    output = BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, data in contents.items():
            archive.writestr(name, data)
    return "bundle", output.getvalue(), "application/zip", digest(manifest)


def generate(kind: str, case: dict[str, Any]) -> tuple[str, bytes, str, str | None]:
    return {"packet": packet, "cap": cap, "husika": husika, "bundle": bundle, "cap-cancel": lambda value: cap(value, cancel=True)}[kind](case)
